### ISSUE TITLE
Harmonic oscillator

### ISSUE THREAD

**Issue by ShofB** [dBiz/VCVRack_Modules#10]
This looks interesting but how is it supposed to work?  How are the sliders supposed to interact with the harmonics and how is this supposed to relate to the inputs for each slider.  I've played around with it but have yet to get a handle on it so any help would be appreciated.  Same questions about the VCA 530

**Comment by dBiz** [comment]
I've modified a little bit the version so you can use the harmonics out with slider and cv, before the outputs just return a full level sine/harmonic, https://www.youtube.com/watch?v=ETsE5OJ1nuM&index=4&list=PL8kruf8Z4FTRuizLAUhLZST05AGohhNRI here's a demo for the release version

**Comment by ShofB** [comment]
Thanks dude, the videos help alot.

On Fri, Nov 24, 2017 at 11:31 AM Giovanni Ghisleni <notifications@github.com>
wrote:

> I've modified a little bit the version so you can use the harmonics out
> with slider and cv, before the outputs just return a full level
> sine/harmonic,
> https://www.youtube.com/watch?v=ETsE5OJ1nuM&index=4&list=PL8kruf8Z4FTRuizLAUhLZST05AGohhNRI
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DETsE5OJ1nuM%26index%3D4%26list%3DPL8kruf8Z4FTRuizLAUhLZST05AGohhNRI&data=02%7C01%7Cshofb%40hotmail.com%7Cff47cb7fa4c54f3b262608d53371e413%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636471486597150872&sdata=64QCZDcJvbOeU%2BJu7Q9gKKs4Xgig88VnXisTCYBdiJs%3D&reserved=0>
> here's a demo for the release version
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FdBiz%2FdBiz%2Fissues%2F10%23issuecomment-346886928&data=02%7C01%7Cshofb%40hotmail.com%7Cff47cb7fa4c54f3b262608d53371e413%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636471486597150872&sdata=QSNkgd8Oq8ln3i7lUzEHnQL29Zyf3cIbGMvHqlZlEXU%3D&reserved=0>,
> or mute the thread
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD4wDGf-jP-Q6NyP4JVh0Y59MUqqsF3hks5s5xlwgaJpZM4QpkNj&data=02%7C01%7Cshofb%40hotmail.com%7Cff47cb7fa4c54f3b262608d53371e413%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636471486597150872&sdata=aflfQphw7y3ZT1AIMk%2BPCEVPTPSzuR8MC07FL%2Fm1zSY%3D&reserved=0>
> .
>
-- 
ShofB

My Web Site
http://www.l-and-l.net

Check out my Soundcloud stream @
https://soundcloud.com/shofb

And my YouTube MyKits demos @
http://www.youtube.com/channel/UCjKNiE1s2YlJYPsAKbe8vhg

**Comment by ShofB** [comment]
ARe there binaries posted?

On Sat, Nov 25, 2017 at 4:43 AM Giovanni Ghisleni <notifications@github.com>
wrote:

> Closed #10
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FdBiz%2FdBiz%2Fissues%2F10&data=02%7C01%7Cshofb%40hotmail.com%7C9ee078c3af55484f18b408d534020ff9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636472105814632395&sdata=yTED2SdBfqUxSkn9WKz2sOMLaROx%2Bt1gLlp06%2FZrtE0%3D&reserved=0>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FdBiz%2FdBiz%2Fissues%2F10%23event-1357817478&data=02%7C01%7Cshofb%40hotmail.com%7C9ee078c3af55484f18b408d534020ff9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636472105814632395&sdata=r%2F2pPXW3fA5GhRJNvC9kkBH4bI6ZhtBZ%2FOGq3Nc2YIU%3D&reserved=0>,
> or mute the thread
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD4wDMPGVftmWc2LWrH-SvkTHVPC4Nu5ks5s6AtQgaJpZM4QpkNj&data=02%7C01%7Cshofb%40hotmail.com%7C9ee078c3af55484f18b408d534020ff9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636472105814632395&sdata=PqRlZPrsA1J%2BIqnilbKXTaq%2FPJ35%2FlM4HBV5ZMkO4ps%3D&reserved=0>
> .
>
-- 
ShofB

My Web Site
http://www.l-and-l.net

Check out my Soundcloud stream @
https://soundcloud.com/shofb

And my YouTube MyKits demos @
http://www.youtube.com/channel/UCjKNiE1s2YlJYPsAKbe8vhg
