### ISSUE TITLE
0.5.1 path issues persist

### ISSUE THREAD

**Issue by metaphorz** [dBiz/VCVRack_Modules#13]
I am unsure if I did everything correctly, but I made this release for Mac: 0.5.1 by downloading source.zip.

I removed dBiz from the plugin folder within the Rack application.

I copied the new made dBiz to the normal plugins directory.

Same problems as before with the UI.

This is worth someone else trying to confirm.

**Comment by dBiz** [comment]
on Mac right ? i've correct the problem for windows in the release binaries.
I'll upload the new code with new module tonight maybe tomorrow ;)

**Comment by dBiz** [comment]
code is update;)

**Comment by metaphorz** [comment]
I did a build here at work and it appears to have fixed the path issue on the Mac. Thanks.
