### ISSUE TITLE
Issue with 0.5.1 plugin manager

### ISSUE THREAD

**Issue by a1laserboy** [dBiz/VCVRack_Modules#16]
Hi

I'm getting an error from the plugin manager in the new Rack 0.5.1:

[warning] Could not get download URL for plugin dBiz

I think you need to update something

![screen shot 2017-12-19 at 20 15 41](https://user-images.githubusercontent.com/13291547/34176881-7606253c-e4f9-11e7-981a-bc7f1df8af31.png)

**Comment by dBiz** [comment]
yep updating right now
