### ISSUE TITLE
Verbo.svg needs a small fix

### ISSUE THREAD

**Issue by davephillips** [dBiz/VCVRack_Modules#18]
Linux Fedora 23
Rack 0.5.x

![dbiz-verbo-corrected](https://user-images.githubusercontent.com/7815938/34649024-0b906396-f374-11e7-81b6-a2913794b7eb.png)
The WAVES label is not linked in your SVG so it does not display. It also needs shifted to the left to be centered correctly. I've corrected it in my copy, see the attachment. Great module, btw. :)

**Comment by dBiz** [comment]
I've updated the svg ;) now should work

**Comment by davephillips** [comment]
I rebuilt your repo on Rack-master (0.6.x), the display problem with Verbo.svg is still there. I corrected it again, it's an easy fix with Inkscape as described in my first note. It's certainly not a big deal, but it is nice to have the label for the function. :)
