### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ghost** [dBiz/VCVRack_Modules#19]
Hi! I just merged your PR in th community repo... after reinstalling i saw the red dot appearing again.. 
right click going to the dBiz modules gives you version 0.5.1 in the right click menu in rack

looks like you forgot to change the version in the makefile

pls check your makefile and json manifest for the plugin manager and fix it.. so that everywhere is the same version number to avoid the red dot

**Comment by dBiz** [comment]
opz my fault i'm correcting right now
