### ISSUE TITLE
Performance Mixer: Tweak

### ISSUE THREAD

**Issue by Coirt** [dBiz/VCVRack_Modules#22]
This is my new favourite mixer but I wish it would convert Mono to Stereo from a mono source. That is connect a mono source and it goes to L/R master making it dual mono. Have to either mult mono to make it stereo or connect L/R to an Output separately just takes more time to do so especially if what is on the chain does not convert to stereo also.

**Comment by dBiz** [comment]
Sorry if it takes soooooo long but now i revamp my PerMixer, mono signals connected to the L input now is automatically converted and panned in stereo ;)
