### ISSUE TITLE
case error latest pull

### ISSUE THREAD

**Issue by davephillips** [dBiz/VCVRack_Modules#26]
Fedora 23 Linux
Rack master (0.6.x)

g++  -Wsuggest-override -std=c++11  -fPIC -I../../include -I../../dep/include -DSLUG=dBiz -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/PerfMixer.cpp.o src/PerfMixer.cpp
src/PerfMixer.cpp:10:27: fatal error: dsp/VUMeter.hpp: No such file or directory
compilation terminated.

VUMeter.hpp should be changed to vumeter.hpp, build then proceeds without problems.

**Comment by dBiz** [comment]
done ;)
