### ISSUE TITLE
Linux build for 0.6

### ISSUE THREAD

**Issue by zeronoises** [dBiz/VCVRack_Modules#29]
[dBiz-0.6.0-lin.zip](https://github.com/dBiz/dBiz/files/1857803/dBiz-0.6.0-lin.zip)

**Comment by dBiz** [comment]
added in release page

**Comment by zeronoises** [comment]
If I use the build above everything is dandy - but if I allow the plugin manager to update it I get the oversized knobs on several modules again. 
I've disabled the update for now...
