### ISSUE TITLE
harmonics verbosc

### ISSUE THREAD

**Issue by joopvdl** [dBiz/VCVRack_Modules#30]
Hey,

I was just watching a video about the verbos hardware version, and I noticed you choose to leave out the fundamental of the harmonic range in the verbosc, and add one extra overtone (the ninth, harmonically speaking).  I was wondering what advantage this has, in your opinion. Just curious :)
Joseph

**Comment by bgracie** [comment]
Thanks so much for making this module!  I really really love it.  I do also think it would be great to have fader/CV over the volume of the fundamental.

**Comment by dBiz** [comment]
;) verbo is updated now, less cpu hungry and a little restyled, @bgracie maybe in a future update i'll add a cv ;)
