### ISSUE TITLE
Big knobs on

### ISSUE THREAD

**Issue by jsmonzani** [dBiz/VCVRack_Modules#31]
Hello!
I've got a visual issue with your release of Utility 0.6.0 Windows: knobs are too large. Maybe a scaling issue. If I swap FlatA.svg component for, say, the smaller DaviesBlack, it works good :)
Cheers and thanks!
JS

![knbos](https://user-images.githubusercontent.com/4018938/38482870-46c239bc-3bd1-11e8-9f2e-6181fea3dfa6.PNG)

**Comment by vogelscheiss** [comment]
Same problem here. Can't tweak, need fixed, thanks.

![image](https://user-images.githubusercontent.com/38222883/38565291-eca444e6-3cae-11e8-9549-777f196046e9.png)

**Comment by jsmonzani** [comment]
@vogelscheiss in the meantime, if this helps, I went to the "res" folder, then backed up FlatA.svg as FlatA.org. I then duplicated DaviesBlack.svg and renamed it FlatA.svg. This works
Beware this might have some side effects on other plugins of dBiz.

**Comment by pfawcett23** [comment]
Same issue on OSX, so it's not platform specific.

And thanks for the notes on a work around.

**Comment by dBiz** [comment]
Here i'm sorry for late, yep is a issue un my svg, i'll reupload all correct svg and correct the components ;)

**Comment by martin-lueders** [comment]
Did you already push the changes to the plugin-manager? I dont get an update yet...

Cheers,
Martin

**Comment by dBiz** [comment]
Finally i've updated the resources, sorry  for the wait ;) 

Cheers!
