### ISSUE TITLE
Rack v1: build directory committed to repository

### ISSUE THREAD

**Issue by cschol** [dBiz/VCVRack_Modules#37]
The `build` directory was committed to the repository during the `v1` port. The repository size is too large for integration in the plugin manager build system.

Please remove the `build` directory from the repository **and** the repository history.

Use, for example, [BFG Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to remove the directory from the git history. Just removing the directory and its content in a commit is **not** enough.

**Comment by dBiz** [comment]
I run BFG cleaner, I'm quite a noob for this check it out ;)
