### ISSUE TITLE
Rack v1: Invalid manifest entries

### ISSUE THREAD

**Issue by cschol** [dBiz/VCVRack_Modules#38]
The manifest validator found invalid entries in the `plugin.json`:

```
Validating dBiz
Missing key: pluginUrl
Missing key: manualUrl
Multiple: invalid tags: UTIL
Transpose: invalid tags: UTIL
Utility: invalid tags: UTIL
```

All modules are missing a `description` field, which is optional.

All other fields mentioned above must be fixed before integration.

For a list of valid tags, see: https://github.com/VCVRack/Rack/blob/v1/src/plugin.cpp#L534

**Comment by dBiz** [comment]
should be fixed now
