### ISSUE TITLE
FourSeq does not recall correctly

### ISSUE THREAD

**Issue by Petervos2018** [dBiz/VCVRack_Modules#40]
Hi Giovanni,
After saving a patch with dBiz FourSeq and re-loading it the lights are not on on the FourSeq, so it does not recall the saved state and does not play any notes (until I manually switch the lights back on).

Love your modules,

Greetings Peter

**Comment by dBiz** [comment]
;) I'll take a look in those days!

**Comment by dBiz** [comment]
Ok was a data json stuff... now should work...  on my machine =) let me know

**Comment by WouterSpekkink** [comment]
I came here because I had the same issue today on Linux. Not sure if the fix was already released as a patch, but if it was, then it doesn't work for Linux at least.

**Comment by Petervos2018** [comment]
Fixed in 1.1.2 !
Thanks and closed.
