### ISSUE TITLE
dBiz / VCA4 bug

### ISSUE THREAD

**Issue by mrshinigami77** [dBiz/VCVRack_Modules#45]
Hello Giovanni and People at dBiz.
I Found a bug on one module, I sent a bug report thinking it was going to dBiz but it ended into VCV Rack general.
So I resend it here. I hope it is the right place to send it, I'm not used to github.

Bug details : 

Details
Operating system: Mac Os Mojave
Rack version: v 1.1.3.
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Audio

Summary
Brand : dBiz
Module : VCA4
v 1.1.0

Issue in Outputs
Outputs 1 to 4 receive signal only from Input D.
Input D goes out perfectly from 1 to 4 outputs.
Steps to reproduce
I fill all A,B,C, D Inputs with 4 waveforms from the same VCO (anyone)
I have an output signal only from the D Input on Outputs 1 to 4 when activating The Unmute button.
I can't get A,B and C inputs to go on any of the Outputs 1 to 4.

-- > Since the signal not working, I don't have the possibility to test the Black Knobs on the knobs, so I don't know if they working fine or not. They are working for the D channel.

**Comment by dBiz** [comment]
Hi, yep my fault in the migration to v1 I've messed up with the output ;)
Now should be fine, let me know

**Comment by mrshinigami77** [comment]
Thank You !
Check it very soon
There will be an update or I redownload the pack dBiz from your github ?
Thanks again !


Le lun. 5 août 2019 à 08:29, Giovanni Ghisleni <notifications@github.com> a
écrit :

**Comment by mrshinigami77** [comment]
Hello Geovanni
Sorry, but still not working.
Maybe i'm doing something wrong on my side.

**Comment by Petervos2018** [comment]
@mrshinigami77  Version 1.1.2 now 10-08-2019 in the Plug in Library 
I think it works now, check it out !

**Comment by mrshinigami77** [comment]
It is Working Perfectly !
Thank you so very much :D
