### ISSUE TITLE
Bene X/Y Input Hazard

### ISSUE THREAD

**Issue by midiguru** [dBiz/VCVRack_Modules#46]
I'm using Nysthi Squonk to send arbitrary values to the X and Y inputs of Bene. (Not the arrow inputs -- I do mean the X and Y inputs.)

This works well (see the 3rd Bene in the attached patch) as long as I carefully set the Squonk outputs to 1, 2, 3, or 4V -- the values normally transmitted by the Pad module. But intermittently, VCV Rack itself will crash if Bene is receiving a voltage input from Squonk that is outside the expected range.

I'd suggest that better out-of-range trapping needs to be done on these inputs.

[dBiz_bene_patch.zip](https://github.com/dBiz/dBiz/files/3490469/dBiz_bene_patch.zip)

**Comment by dBiz** [comment]
I've redesigned the bene function a bit ;) 
Sure I'll make a Mk2
