### ISSUE TITLE
v2: References to custom fonts stored across frames

### ISSUE THREAD

**Issue by cschol** [dBiz/VCVRack_Modules#49]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example (but there might be others):
```
BeneDisplay()                                                     
{                                                                      
    font = (APP->window->loadFont(asset::plugin(pluginInstance, "res/DOTMATRI.ttf")));
}       
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by cschol** [comment]
Will there be a fix for this issue? This is a high-priority defect since it crashes the VST. Thank you!

**Comment by dBiz** [comment]
Hi, sorry for late reply, sure i will fix as soon as possible, maybe a couple of days ;)

**Comment by cschol** [comment]
Sounds good. Thanks.

**Comment by dBiz** [comment]
Now with the latest source should be fixed ;) i'm not really a coder, hope it works...
I've tested in cubase and seems good.

**Comment by cschol** [comment]
Please submit an updated SHA to the library issue. Thanks.

**Comment by dBiz** [comment]
Done ;)
