### ISSUE TITLE
Bene Y direction switch not working in 2.0

### ISSUE THREAD

**Issue by SergeProtectorMusic** [dBiz/VCVRack_Modules#51]
The Y Direction switch in Bene can turn off and on with a trigger or a click, but it doesn't change the direction. X works fine, and I haven't found any other problems. 

Anyway, great modules — Thanks for all the cool stuff you build!

**Comment by dBiz** [comment]
Hi, yep it's fixed in the source code. I'll make a build soon as i fix some other issue ;)

**Comment by SergeProtectorMusic** [comment]
Thanks!
