### ISSUE TITLE
v2: plugin.dll committed to repository

### ISSUE THREAD

**Issue by cschol** [dBiz/VCVRack_Modules#53]
The `plugin.dll` has been committed to the repository. This is not acceptable as it significantly increases the repository size when cloning in the Plugin Manager build system.

Please remove the `plugin.dll` from the repository. Please note, that it is **NOT** enough to just remove and commit. You must remove the `plugin.dll` binary from the **history** of the repository.

Please use a tool like [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to accomplish this.

**Comment by dBiz** [comment]
Sorry for that ;) I've fixed now

**Comment by cschol** [comment]
You just removed the `plugin.dll` with a commit. It is still part of the repository history. Please see my instructions above on how to remove it from the history. A commit is **not enough**.

**Comment by dBiz** [comment]
Hi, sorry for that, my git and command prompt knowledge are quite low =(
I've tried BFG but I'm not sure ;)  I apparently clean on my desktop but I've an error when push 
![image](https://user-images.githubusercontent.com/12683589/147285666-23ea0247-a04d-4415-9c36-0c24221391bb.png)

**Comment by dBiz** [comment]
I've tried to fetch or pull, using BFG again but I've got the error again ...
Really sorry for that =(

**Comment by cschol** [comment]
Did you use the `--mirror` flag to clone a fresh copy of your repo?

**Comment by dBiz** [comment]
Yep, I followed the BFG instructions... I'll make another attempt later

**Comment by dBiz** [comment]
I've installed git for windows and repeated the procedure ... I've launched java -jar bfg-1.14.0.jar --delete-files plugin.dll dBiz.git
and now on git push I've got this... 
![image](https://user-images.githubusercontent.com/12683589/147331644-17a0c54a-d787-4443-a3c7-6da6b2351600.png)

**Comment by cschol** [comment]
I think the problem is that is requires a `force push` with `git push --force`. **BE CAREFUL** with that command. It will overwrite your repository on Github without asking any more questions. I would ensure that you have a copy locally just to be sure.

**Comment by dBiz** [comment]
Recloned, recleaned, and force push ... now I've got this =(  
![image](https://user-images.githubusercontent.com/12683589/147335866-2d8ef001-97ce-4804-aa95-8a6b4945e945.png)
Again sorry for my noob knowledge ;)

**Comment by dBiz** [comment]
after reading this
https://github.com/rtyley/bfg-repo-cleaner/issues/36
 I manage to push the clean repo ... ( I hope )
Give it a look plz ;)

Happy Xmas!

**Comment by cschol** [comment]
Looks good now. Thank you!
