### ISSUE TITLE
Cycle button failure of Contorno

### ISSUE THREAD

**Issue by firolightfog** [dBiz/VCVRack_Modules#55]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/34127628/147604892-339a2368-a165-4757-9fde-889028d54b8b.png">

<img width="182" alt="image" src="https://user-images.githubusercontent.com/34127628/147605392-bea708c6-0b1e-426b-88d9-52407bd21205.png">

The CH CYCLE push button is buggy. According to the label all four of them are switched off but some of them are still shinning blue.

Are the four IN inputs for a hidden VCA? They're either broken or I completely misunderstand their function.

**Comment by dBiz** [comment]
Hi, the button should be fixed now, and the inputs are just triggers for the cycle ;)

**Comment by firolightfog** [comment]
Keeping an eye on the VCV Library for this update.

I meant what's the input at the bottom?
<img width="261" alt="image" src="https://user-images.githubusercontent.com/34127628/149621550-7429ecce-2f51-49f7-81b4-db1031c0eaed.png">

**Comment by dBiz** [comment]
![Contorno](https://user-images.githubusercontent.com/12683589/149652967-ff411c38-9791-4a92-8afd-5e06f7312c98.jpg)
Hehe I know I have to write some manuals ;)

**Comment by firolightfog** [comment]
Oh, I get it now! Even if it didn't work I was sure that it should be an audio input that can be shaped by the envelope. Thanks for the clarification!

**Comment by rifsc** [comment]
Hi, Contorno is great plugin, I used it a lot within Rack 1, however now, even after update Your collection to v. 2.0.4, cycle buttons are still unavailable to turn off. I dunno, it is not happening every time but mostly when I open Contorno, one or more cycle buttons are on (light blue) and there is no possibility to change it. Thanks a lot for Your work! Cheers!

**Comment by dBiz** [comment]
Yep, hopefully I've fixed now, working well on my machine, hope on others too ;)

**Comment by rifsc** [comment]
It looks like problem is solved :) Thank U! As I said, use Your collection a lot, great stuff!
