### ISSUE TITLE
Persistent theme color in browser and as default

### ISSUE THREAD

**Issue by Eurikon** [dBiz/VCVRack_Modules#57]
Hi there, and thanks for your plugin!

So, in an ongoing effort to get many developers to make there plugins behave the same with themes, i wanted to ask you for the following:

With other plugins that provide the option for changing and saving the default theme colour,
those plugins represent their module screenshots in the browser in the saved default colour.

ie: when a module its default is set to dark themed, all the modules in that plugin show up as dark themed in the browser.

Some plugins with such behaviour:
Impromptu
Bogaudio
Geodesics
Surge
Submarine
Count Modula

These plugins modules also retain the default color when inserting a new instance, as they allow it to be the default.

Would be really nice if your plugin modules followed this behaviour as well.

Cheers!
Latif

**Comment by dBiz** [comment]
Hi, sorry for the late reply, yep I've noticed that but my coding skills can't find how to do that =( any advice? 
The suggested modules are a little bit difficult to reverse eng. for me hehehe

**Comment by dBiz** [comment]
;) Fixed now hopefully
