### ISSUE TITLE
DualFilter right Cent. Freq. knob always show 8211.6 Hz

### ISSUE THREAD

**Issue by jaynothin** [dBiz/VCVRack_Modules#58]
DualFilter 2.0.3

As the title say, there is a small bug that a friend told me about.

The dual filter B channel top knob (Center Freq) always displays 8211.6 Hz no matter where it is dialed too. 🤔  (See image 1 and 2)

edit: - Also it doesn't reflect any values added in the input prompt 😮 

 
But it is not major and it doesn't affect the sound. 😄  

Image 1 ![image 01](https://user-images.githubusercontent.com/74117050/169671818-ad929bcb-dc28-4b7b-bc70-7a233b417dff.png)
Image 2 ![image 02](https://user-images.githubusercontent.com/74117050/169671933-546a2eb9-d9e1-40f3-aeb9-c305557acc0e.png)

Windows 10
Rack 2.1.0

**Comment by dBiz** [comment]
Fixed ;)
