### ISSUE TITLE
Windows build errors 171117 - Color related?

### ISSUE THREAD

**Issue by djpeterso23662** [dBiz/VCVRack_Modules#7]
$ make VERSION=0.5.0
g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.0 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/Chord.cpp.o src/Chord.cpp
In file included from src/dBiz.hpp:2:0,
                 from src/Chord.cpp:10:
src/dBizComponent.hpp:363:1: error: expected class-name before '{' token
 {
 ^
src/dBizComponent.hpp: In constructor 'rack::OrangeLight::OrangeLight()':
src/dBizComponent.hpp:366:3: error: 'addColor' was not declared in this scope
   addColor(COLOR_ORANGE);
   ^~~~~~~~
src/dBizComponent.hpp:366:3: note: suggested alternative: 'NVGcolor'
   addColor(COLOR_ORANGE);
   ^~~~~~~~
   NVGcolor
src/dBizComponent.hpp: At global scope:
src/dBizComponent.hpp:371:1: error: expected class-name before '{' token
 {
 ^
src/dBizComponent.hpp: In constructor 'rack::CyanLight::CyanLight()':
src/dBizComponent.hpp:374:3: error: 'addColor' was not declared in this scope
   addColor(COLOR_CYAN);
   ^~~~~~~~
src/dBizComponent.hpp:374:3: note: suggested alternative: 'NVGcolor'
   addColor(COLOR_CYAN);
   ^~~~~~~~
   NVGcolor
src/dBizComponent.hpp: At global scope:
src/dBizComponent.hpp:379:1: error: expected class-name before '{' token
 {
 ^
src/dBizComponent.hpp: In constructor 'rack::PurpleLight::PurpleLight()':
src/dBizComponent.hpp:382:3: error: 'addColor' was not declared in this scope
   addColor(COLOR_PURPLE);
   ^~~~~~~~
src/dBizComponent.hpp:382:3: note: suggested alternative: 'NVGcolor'
   addColor(COLOR_PURPLE);
   ^~~~~~~~
   NVGcolor
make: *** [../../compile.mk:54: build/src/Chord.cpp.o] Error 1

**Comment by dBiz** [comment]
yep due to changes in dev ... i'm fixing all my modules right now ;)

**Comment by dBiz** [comment]
try with latest commit ;)

**Comment by djpeterso23662** [comment]
Successful compile on Windows 10, using Rack dev from 17 Nov 2017.  Thanks so much for your time!  Great set of modules!
