### ISSUE TITLE
0.5.0 -- graphics are not coming out correctly on Mac

### ISSUE THREAD

**Issue by metaphorz** [dBiz/VCVRack_Modules#8]
![screenshot 2017-11-21 13 08 37_preview](https://user-images.githubusercontent.com/3519631/33091592-29990dec-cebd-11e7-9e3e-2c09882958dc.png)

**Comment by nay-seven** [comment]
For info, a friend give me the tips : it's a path issue, if you add the folder directly in the app, works ;-)

**Comment by metaphorz** [comment]
Good tip  as it is a path issue.  in dBizComponent.hpp, the following is called:

assetGlobal("plugins/res/knobs/VerboL.svg")

as one example. so, what would one change the path to using Rack from Mac Applications?
I thought that on the Mac, it was looking for everything under ~/Documents/Rack, so the path
should be right, no? I've tried:

(1) removing "plugins" to get the path "res/...."   and
(2) adding "dBiz" as follows:  "plugins/dBiz/res/knobs....

and remade. neither has worked

**Comment by metaphorz** [comment]
Or perhaps, just hardcoding an absolute path? e.g.,

/Users/X/Rack/.....

**Comment by metaphorz** [comment]
@nay-seven: thanks - that worked. I had been using an edited source. BenePads still crashes Rack for me. The other modules now look right though.

**Comment by dBiz** [comment]
i'll check path issue ass soon as possible ;) for BenePads sure something wrong with the code ...
i'll check/ask for help too

**Comment by blackearth2014** [comment]
Also for the Windows platform, the graphics are not showing up properly.

**Comment by dBiz** [comment]
Can you give me some more info? what you download, OS, Rack version?

**Comment by robertocolabene** [comment]
also for me on windows 8.1, rack 0.5, downloaded from here https://github.com/dBiz/dBiz/releases

**Comment by dBiz** [comment]
I've uploaded a cleaned version, can you also post a screenshot? Seems to be a folder problem, on windows you should have this structure: VCVRack/plugins/dbiz/ 
I checked again my component code but on all my machines it works so I have to depend on your feedback guys ;)

**Comment by robertocolabene** [comment]
confirmed, it works well when placed on vcv folder, so you cannot place it in the documents/plugins

**Comment by metaphorz** [comment]
on mac OSX -- works fine (with the exception of BenePads if the plugin folder is placed in the Application contents where it is supposed to go -- the plugins folder inside of the Rack app). If the plugin is placed under ~/Documents/Rack/plugins (where all others go), the path must be wrong because the graphics do not include text or plug holes). It is definitely a path issue.

As for BenePads, I can include part of the dump below if that helps any:

Process:               Rack [77797]
Path:                  /Applications/Rack.app/Contents/MacOS/Rack
Identifier:            com.vcvrack.rack
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Rack [77797]
User ID:               501

Date/Time:             2017-11-22 10:37:45.056 -0600
OS Version:            Mac OS X 10.13.1 (17B48)
Report Version:        12
Anonymous UUID:        D6D40B3C-0FAD-6B61-AE53-2A01468BB84E

Sleep/Wake UUID:       EDCFCD31-0EB9-4A11-A01B-94C8F5990C8E

Time Awake Since Boot: 230000 seconds
Time Since Wake:       1700 seconds

System Integrity Protection: enabled

Crashed Thread:        4

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000603ff788b380
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x603ff788b380:
    MALLOC_NANO            0000600000000000-0000600000600000 [ 6144K] rw-/rwx SM=PRV  
--> 
    MALLOC_NANO            0000604000000000-0000604000400000 [ 4096K] rw-/rwx SM=PRV  

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff60fccd12 __open_nocancel + 10
1   libsystem_c.dylib             	0x00007fff60f09440 fopen + 72
2   com.vcvrack.rack              	0x00000001051a1cd3 nsvgParseFromFile + 35
3   com.vcvrack.rack              	0x00000001051ab10f std::__1::shared_ptr<rack::SVG> std::__1::shared_ptr<rack::SVG>::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&) + 95
4   com.vcvrack.rack              	0x00000001051a3e77 rack::SVG::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 279
5   plugin.dylib                  	0x000000010565ddb9 BenePadsWidget::BenePadsWidget() + 1097
6   plugin.dylib                  	0x0000000105689a5f rack::Model* rack::createModel<BenePadsWidget, rack::ModelTag>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, rack::ModelTag)::TModel::createModuleWidget() + 31 (rack.hpp:26)
7   com.vcvrack.rack              	0x00000001051b21ee rack::ModelItem::onAction(rack::EventAction&) + 30
8   com.vcvrack.rack              	0x00000001051eb95b virtual thunk to rack::MenuItem::onDragDrop(rack::EventDragDrop&) + 59
9   com.vcvrack.rack              	0x00000001051a201c rack::mouseButtonCallback(GLFWwindow*, int, int, int) + 364
10  com.vcvrack.rack              	0x00000001051a3240 rack::guiRun() + 352
11  com.vcvrack.rack              	0x00000001051ab5aa main + 698
12  com.vcvrack.rack              	0x000000010518d3e4 start + 52

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff60fcd6da __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff6110706a _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff61106c4d start_wqthread + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff60fcd6da __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff6110726f _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff61106c4d start_wqthread + 13

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff60fc3e76 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff60fc3390 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff397fddd5 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff397fd127 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff397fc797 CFRunLoopRunSpecific + 487
5   com.apple.AppKit              	0x00007fff36f4c2d1 _NSEventThread + 184
6   libsystem_pthread.dylib       	0x00007fff611076c1 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff6110756d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff61106c5d thread_start + 13

Thread 4 Crashed:
0   plugin.dylib                  	0x000000010565cff9 BenePads::step() + 393 (BenePads.cpp:66)
1   com.vcvrack.rack              	0x000000010518df4e rack::engineRun() + 366
2   com.vcvrack.rack              	0x000000010518ecfd void* std::__1::__thread_proxy<std::__1::tuple<void (*)()> >(void*) + 93
3   libsystem_pthread.dylib       	0x00007fff611076c1 _pthread_body + 340
4   libsystem_pthread.dylib       	0x00007fff6110756d _pthread_start + 377
5   libsystem_pthread.dylib       	0x00007fff61106c5d thread_start + 13

Thread 4 crashed with X86 Thread State (64-bit):
  rax: 0x000060400005ba20  rbx: 0x000000010526fe38  rcx: 0xfffffffffdd86510  rdx: 0x0000000000000004
  rdi: 0x00007f92fde63fe0  rsi: 0x0000000000000004  rbp: 0x00007000029dae40  rsp: 0x00007000029dae40
   r8: 0x0000000000000011   r9: 0x00007f92fdd864cc  r10: 0x0000604000271f40  r11: 0x0000000000000000
  r12: 0x00007f92fde63fe0  r13: 0x000060c0004e79f8  r14: 0x0000000000000000  r15: 0x000060c0004e7a00
  rip: 0x000000010565cff9  rfl: 0x0000000000010246  cr2: 0x0000603ff788b380
  
Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14

**Comment by t0m5k1** [comment]
I get the graphics but no sockets or knobs Win10 64 VCV 050

**Comment by dBiz** [comment]
you have to put the folder in application/plugins till i fix the path issue
you should have vcvrack/plugins/dBiz

**Comment by t0m5k1** [comment]
Sorted :) thnx
