### ISSUE TITLE
Module BenePad cause crash of Rack mac

### ISSUE THREAD

**Issue by Motopomp** [dBiz/VCVRack_Modules#9]
when we choose this module the application crash and exit on mac

**Comment by dBiz** [comment]
yep i know... i'm working on that ;) just studying the dubug i have ;) solution will come soon

**Comment by Motopomp** [comment]
I have absolutely no doubt that you can find a solution. If I can help you?
Unfortunately I do not know coded, but may be providing you a "log" or others, but I'm not sure how to get it.
I tried to launch Rack from the contents of "Rack.app" in "Rack.app/Contents/MacOS/" it launches me the application and the terminal, when I try to launch the faulty module and that the crash this produces that tells me only "Segmentation Fault: 11" and next line "logout".
I do not know if that helps you ......
thank you in advance

**Comment by dBiz** [comment]
I've changed a little bit the code for BenePads, let me now if works

**Comment by metaphorz** [comment]
Works for me. Not crashing. Not sure how it works X,Y,G and a 4x4

**Comment by dBiz** [comment]
it's basically a keyboard for bene with xy position and a gate ;) just connect and play, i'll upload a video patch soon
